spring.application.name=runmate-springboot

# datasource (oracle)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1522/xepdb1
spring.datasource.username=javauser
spring.datasource.password=java1234

#jpa setting
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.open-in-view=true

# OpenAPI 문서(/v3/api-docs) 제공 기능 비활성화
springdoc.api-docs.enabled=true

# Swagger UI 화면 제공 기능 비활성화
springdoc.swagger-ui.enabled=true

# 스프링 시큐리티의 요청 처리 과정과 필터 체인의 동작을 확인
logging.level.org.springframework.security.web=TRACE